[BUILD] Fix problems at cross-compiling
Hello,

I'm trying to cross-compile kbd-1.14. I configured it with the following arguments:

--prefix=/usr --build=i686-unknown-linux-gnu --host=x86_64-unknown-linux-gnu --disable-nls

I get the following error message:

configure: error: cannot check setpgrp when cross compiling

I can fix it by adding ac_cv_func_setpgrp_void=yes to the configure arguments list,
but I wonder if this is the normal and recommended way to proceed or if it is a bug.

Also, I cannot run "make" successfully because of the following error message:

mapscrn-xmalloc.o: In function `xrealloc':
xmalloc.c:(.text+0x67): undefined reference to `rpl_realloc'
mapscrn-xmalloc.o: In function `xmalloc':
xmalloc.c:(.text+0xa7): undefined reference to `rpl_malloc'
mapscrn-kdmapop.o: In function `getunimap':
kdmapop.c:(.text+0x248): undefined reference to `rpl_malloc'
collect2: ld returned 1 exit status

I can fix it by adding ac_cv_func_malloc_0_nonnull=yes and ac_cv_func_realloc_0_nonnull=yes
to the configure arguments list. I have the same doubt as before.

Signed-off-by: Alexey Gladkov <legion@altlinux.org>