libkbdfile: Fix problem with undeclared sym_gzopen
A compile error occurs on certain systems:

kbdfile-zlib.c: In function 'dlopen_note':
elf-note.h:27:30: error: 'sym_gzopen' undeclared (first use in this function); did you mean 'sym_gzopen64'?
   27 | #define DLSYM_ARG(symbol__) &sym_##symbol__, STRINGIFY(symbol__),

kbdfile-zlib.c: In function 'kbdfile_decompressor_zlib': kbdfile-zlib.c:61:15: error: implicit declaration of function 'sym_gzopen'; did you mean 'sym_gzopen64'?
 [-Wimplicit-function-declaration]
   61 |         gzf = sym_gzopen(file->pathname, "rb");

The problem arises because if -D_FILE_OFFSET_BITS=64 is specified, which
in zlib ultimately makes gzopen a macro that expands to gzopen64.
DECLARE_SYM(gzopen) from elf-note.h then expands gzopen to gzopen64,
resulting in sym_gzopen64 declared. That's why no sym_gzopen exists.

Link: https://github.com/legionus/kbd/pull/150
Suggested-by: Jan Čermák <sairon@sairon.cz>
Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Alexey Gladkov <legion@kernel.org>